### ISSUE TITLE
[JS Automation Lab] stage 1

### ISSUE THREAD

**Issue by artiombond** [memuka13/firstProject#5]
Need to make some corrections before checking your code further:
1. master/main branch should be empty
2. Solutions to each unit (from 3 to 8) should be done in the appropriate branches (e.g. unit-3, unit-4, etc.) in separate files.
3. Create pull-requests for each of the units you are studying (from 3 to 8).
Format the code.

**Comment by memuka13** [comment]
Please review modified project.

Thanks
